/** Shared SQLite/Turso DDL. Keep applied migrations immutable. */
export const initialTables = {
  capi_metadata: `
    key TEXT PRIMARY KEY NOT NULL,
    value TEXT NOT NULL`,
  capi_schema_migrations: `
    version INTEGER PRIMARY KEY NOT NULL CHECK (version >= 1),
    name TEXT NOT NULL,
    checksum TEXT NOT NULL,
    applied_at INTEGER NOT NULL`,
  capi_applied_operations: `
    id TEXT PRIMARY KEY NOT NULL,
    kind TEXT NOT NULL,
    actor_id TEXT NOT NULL,
    input_digest TEXT NOT NULL,
    committed_revision INTEGER NOT NULL CHECK (committed_revision >= 0),
    result_json TEXT NOT NULL,
    created_at INTEGER NOT NULL`,
  capi_settings: `
    namespace TEXT PRIMARY KEY NOT NULL,
    value_json TEXT NOT NULL,
    revision INTEGER NOT NULL CHECK (revision >= 0)`,
  capi_accounts: `
    id INTEGER PRIMARY KEY AUTOINCREMENT CHECK (id >= 0),
    domain TEXT NOT NULL,
    upstream_user_id TEXT,
    login TEXT,
    label TEXT,
    enabled INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
    deleting_at INTEGER,
    deleted_at INTEGER,
    credential_revision INTEGER NOT NULL DEFAULT 0 CHECK (credential_revision >= 0),
    validation_json TEXT NOT NULL DEFAULT '{}',
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    UNIQUE (domain, upstream_user_id)`,
  capi_account_credentials: `
    account_id INTEGER PRIMARY KEY NOT NULL REFERENCES capi_accounts(id) ON DELETE RESTRICT,
    oauth_value TEXT NOT NULL,
    updated_at INTEGER NOT NULL`,
  capi_providers: `
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    enabled INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
    deleted_at INTEGER,
    payload_json TEXT NOT NULL DEFAULT '{}',
    revision INTEGER NOT NULL DEFAULT 0 CHECK (revision >= 0),
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL`,
  capi_provider_secrets: `
    provider_id TEXT PRIMARY KEY NOT NULL REFERENCES capi_providers(id) ON DELETE CASCADE,
    api_key TEXT,
    headers_json TEXT NOT NULL DEFAULT '{}',
    updated_at INTEGER NOT NULL`,
  capi_service_secrets: `
    service TEXT PRIMARY KEY NOT NULL,
    secret_value TEXT NOT NULL,
    updated_at INTEGER NOT NULL`,
  capi_gateway_credentials: `
    id TEXT PRIMARY KEY NOT NULL,
    digest TEXT NOT NULL UNIQUE,
    label TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    revoked_at INTEGER,
    last_used_at INTEGER`,
  capi_inference_credentials: `
    digest TEXT PRIMARY KEY NOT NULL,
    id TEXT NOT NULL UNIQUE,
    kind TEXT NOT NULL,
    principal_id TEXT NOT NULL,
    label TEXT,
    enabled INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
    scopes_json TEXT NOT NULL DEFAULT '[]',
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    revoked_at INTEGER`,
  capi_ip_allowlist: `
    ip TEXT PRIMARY KEY NOT NULL,
    label TEXT,
    enabled INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
    source TEXT NOT NULL DEFAULT 'manual' CHECK (source IN ('authenticated', 'dashboard', 'manual')),
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    last_seen_at INTEGER`,
  capi_admin: `
    id INTEGER PRIMARY KEY NOT NULL CHECK (id = 1),
    password_hash TEXT NOT NULL,
    session_version INTEGER NOT NULL CHECK (session_version >= 1),
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL`,
  capi_admin_sessions: `
    token_hash TEXT PRIMARY KEY NOT NULL,
    admin_id INTEGER NOT NULL DEFAULT 1 REFERENCES capi_admin(id) ON DELETE CASCADE,
    csrf_hash TEXT NOT NULL,
    session_version INTEGER NOT NULL,
    created_at INTEGER NOT NULL,
    last_seen_at INTEGER NOT NULL,
    expires_at INTEGER NOT NULL`,
  capi_setup_codes: `
    digest TEXT PRIMARY KEY NOT NULL,
    created_at INTEGER NOT NULL,
    expires_at INTEGER NOT NULL,
    consumed_at INTEGER,
    invalidated_at INTEGER`,
  capi_device_login_intents: `
    id TEXT PRIMARY KEY NOT NULL,
    admin_id INTEGER NOT NULL REFERENCES capi_admin(id) ON DELETE CASCADE,
    domain TEXT NOT NULL,
    device_code TEXT NOT NULL,
    user_code TEXT NOT NULL,
    verification_uri TEXT NOT NULL,
    interval_seconds INTEGER NOT NULL CHECK (interval_seconds > 0),
    created_at INTEGER NOT NULL,
    expires_at INTEGER NOT NULL,
    canceled_at INTEGER,
    completed_at INTEGER,
    account_id INTEGER REFERENCES capi_accounts(id) ON DELETE RESTRICT,
    payload_json TEXT NOT NULL DEFAULT '{}'`,
  capi_oauth_codes: `
    digest TEXT PRIMARY KEY NOT NULL,
    client_id TEXT NOT NULL,
    redirect_uri TEXT NOT NULL,
    scopes_json TEXT NOT NULL,
    state TEXT NOT NULL,
    code_challenge TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    expires_at INTEGER NOT NULL,
    consumed_at INTEGER`,
  capi_oauth_families: `
    id TEXT PRIMARY KEY NOT NULL,
    principal_id TEXT,
    client_id TEXT,
    scopes_json TEXT NOT NULL DEFAULT '[]',
    created_at INTEGER NOT NULL,
    expires_at INTEGER,
    revoked_at INTEGER`,
  capi_oauth_access: `
    digest TEXT PRIMARY KEY NOT NULL,
    family_id TEXT NOT NULL REFERENCES capi_oauth_families(id) ON DELETE RESTRICT,
    principal_id TEXT NOT NULL,
    client_id TEXT NOT NULL,
    scopes_json TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    expires_at INTEGER,
    revoked_at INTEGER`,
  capi_oauth_refresh: `
    digest TEXT PRIMARY KEY NOT NULL,
    family_id TEXT NOT NULL REFERENCES capi_oauth_families(id) ON DELETE RESTRICT,
    principal_id TEXT NOT NULL,
    client_id TEXT NOT NULL,
    scopes_json TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    expires_at INTEGER,
    revoked_at INTEGER,
    consumed_at INTEGER`,
  capi_usage_minutes: `
    minute INTEGER NOT NULL CHECK (minute >= 0),
    model TEXT NOT NULL DEFAULT '',
    input_tokens INTEGER NOT NULL DEFAULT 0 CHECK (input_tokens >= 0),
    output_tokens INTEGER NOT NULL DEFAULT 0 CHECK (output_tokens >= 0),
    request_count INTEGER NOT NULL DEFAULT 0 CHECK (request_count >= 0),
    PRIMARY KEY (minute, model)`,
  capi_usage_lifetime: `
    id INTEGER PRIMARY KEY NOT NULL CHECK (id = 1),
    input_tokens INTEGER NOT NULL DEFAULT 0 CHECK (input_tokens >= 0),
    output_tokens INTEGER NOT NULL DEFAULT 0 CHECK (output_tokens >= 0),
    request_count INTEGER NOT NULL DEFAULT 0 CHECK (request_count >= 0),
    first_request_at INTEGER`,
  capi_routing_minutes: `
    minute INTEGER NOT NULL CHECK (minute >= 0),
    dimension_key TEXT NOT NULL,
    account_id INTEGER REFERENCES capi_accounts(id) ON DELETE RESTRICT,
    payload_json TEXT NOT NULL DEFAULT '{}',
    PRIMARY KEY (minute, dimension_key)`,
  capi_activity: `
    id TEXT PRIMARY KEY NOT NULL,
    generation INTEGER NOT NULL CHECK (generation >= 0),
    created_at INTEGER NOT NULL,
    expires_at INTEGER NOT NULL,
    kind TEXT NOT NULL,
    account_id INTEGER REFERENCES capi_accounts(id) ON DELETE RESTRICT,
    payload_json TEXT NOT NULL,
    payload_bytes INTEGER NOT NULL CHECK (payload_bytes >= 0)`,
  capi_debug: `
    id TEXT PRIMARY KEY NOT NULL,
    generation INTEGER NOT NULL CHECK (generation >= 0),
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    expires_at INTEGER NOT NULL,
    status TEXT NOT NULL,
    replayable INTEGER NOT NULL DEFAULT 0 CHECK (replayable IN (0, 1)),
    account_id INTEGER REFERENCES capi_accounts(id) ON DELETE RESTRICT,
    provider_id TEXT REFERENCES capi_providers(id) ON DELETE RESTRICT,
    payload_json TEXT NOT NULL,
    payload_bytes INTEGER NOT NULL CHECK (payload_bytes >= 0)`,
  capi_imports: `
    id TEXT PRIMARY KEY NOT NULL,
    manifest_digest TEXT NOT NULL UNIQUE,
    committed_revision INTEGER NOT NULL CHECK (committed_revision >= 0),
    completed_at INTEGER NOT NULL,
    counts_json TEXT NOT NULL`,
  capi_process_runs: `
    id TEXT PRIMARY KEY NOT NULL,
    started_at INTEGER NOT NULL,
    last_flush_at INTEGER,
    ended_at INTEGER,
    clean INTEGER NOT NULL DEFAULT 0 CHECK (clean IN (0, 1)),
    payload_json TEXT NOT NULL DEFAULT '{}'`,
  capi_collection_gaps: `
    id TEXT PRIMARY KEY NOT NULL,
    process_run_id TEXT REFERENCES capi_process_runs(id) ON DELETE RESTRICT,
    started_at INTEGER NOT NULL,
    ended_at INTEGER,
    kind TEXT NOT NULL CHECK (kind IN ('known', 'unknown')),
    lost_records INTEGER CHECK (lost_records >= 0),
    lost_bytes INTEGER CHECK (lost_bytes >= 0),
    payload_json TEXT NOT NULL DEFAULT '{}'`,
} as const

export const initialIndexes = {
  capi_operations_created: "capi_applied_operations(created_at)",
  capi_accounts_enabled: "capi_accounts(enabled, deleting_at, deleted_at)",
  capi_providers_enabled: "capi_providers(enabled, deleted_at)",
  capi_inference_principal:
    "capi_inference_credentials(principal_id, revoked_at)",
  capi_admin_sessions_expiry: "capi_admin_sessions(expires_at)",
  capi_admin_sessions_admin: "capi_admin_sessions(admin_id)",
  capi_setup_codes_expiry: "capi_setup_codes(expires_at)",
  capi_device_intents_expiry: "capi_device_login_intents(expires_at)",
  capi_device_intents_admin: "capi_device_login_intents(admin_id)",
  capi_device_intents_account: "capi_device_login_intents(account_id)",
  capi_oauth_codes_expiry: "capi_oauth_codes(expires_at)",
  capi_oauth_families_principal:
    "capi_oauth_families(principal_id, revoked_at)",
  capi_oauth_access_family: "capi_oauth_access(family_id, revoked_at)",
  capi_oauth_access_principal: "capi_oauth_access(principal_id, revoked_at)",
  capi_oauth_refresh_family: "capi_oauth_refresh(family_id, revoked_at)",
  capi_oauth_refresh_principal: "capi_oauth_refresh(principal_id, revoked_at)",
  capi_routing_account: "capi_routing_minutes(account_id, minute)",
  capi_activity_generation: "capi_activity(generation, created_at)",
  capi_activity_expiry: "capi_activity(expires_at)",
  capi_activity_account: "capi_activity(account_id)",
  capi_debug_generation: "capi_debug(generation, created_at)",
  capi_debug_expiry: "capi_debug(expires_at)",
  capi_debug_account: "capi_debug(account_id)",
  capi_debug_provider: "capi_debug(provider_id)",
  capi_process_runs_clean: "capi_process_runs(clean, started_at)",
  capi_gaps_process: "capi_collection_gaps(process_run_id)",
} as const

export const initialMigration = {
  version: 1,
  name: "initial",
  statements: [
    ...Object.entries(initialTables).map(
      ([name, columns]) => `CREATE TABLE ${name} (${columns}\n)`,
    ),
    ...Object.entries(initialIndexes).map(
      ([name, target]) => `CREATE INDEX ${name} ON ${target}`,
    ),
    "INSERT INTO capi_usage_lifetime (id) VALUES (1)",
  ],
} as const
