import type { ModelRedirectVerbosity } from "~/lib/model-redirect"
import type {
  ResponseInputItem,
  ResponsesPayload,
} from "~/services/copilot/create-responses"

import { isModelFallbackActive } from "~/lib/model-fallback"

export function getResponsesVerbosity(
  payload: ResponsesPayload,
): ModelRedirectVerbosity | undefined {
  const verbosity = payload.text?.verbosity
  return verbosity === "low" || verbosity === "medium" || verbosity === "high" ?
      verbosity
    : undefined
}

export function applyResponsesVerbosity(
  payload: ResponsesPayload,
  verbosity: ModelRedirectVerbosity | undefined,
): void {
  if (!verbosity) return
  payload.text = payload.text ? { ...payload.text, verbosity } : { verbosity }
}

export const getResponsesRequestOptions = (
  payload: ResponsesPayload,
): { vision: boolean; initiator: "agent" | "user" } => {
  const vision = hasVisionInput(payload)
  const initiator = hasAgentInitiator(payload) ? "agent" : "user"

  return { vision, initiator }
}

/**
 * Apply the latest compaction boundary, expand proxy-generated summaries,
 * and strip encrypted_content from reasoning items.
 *
 * A compaction item replaces historical input that precedes it. Retaining
 * superseded turns defeats compaction and can make the wire payload grow
 * without bound. Codex compacted windows intentionally prepend fresh
 * bootstrap context before the marker, though: additional tool declarations
 * plus developer/user records tagged with the active turn_id. Preserve that
 * current-window prefix, the latest compaction item, and all later input.
 *
 * Proxy-generated "cmp_" items have base64-encoded summaries we can decode.
 * Native compaction items carry opaque, token-bound state and must remain
 * intact. Account routing is stable for a client session, including the
 * stable first-account fallback when no session identifier is supplied.
 *
 * Reasoning items also have encrypted_content stripped for the same reason.
 */
export const expandCompactionItems = (payload: ResponsesPayload): void => {
  if (!Array.isArray(payload.input)) return

  const latestCompactionIndex = findLatestCompactionIndex(payload.input)
  const compactedInput =
    latestCompactionIndex === -1 ?
      payload.input
    : preserveCompactionBootstrap(payload.input, latestCompactionIndex)

  payload.input = compactedInput.map((item) => {
    const record = item as Record<string, unknown>

    // Convert only proxy-generated compaction items into plain messages.
    // Native opaque items must be forwarded unchanged.
    if (record.type === "compaction") {
      const summary = extractCompactionSummary(record)
      if (!summary) return item

      return {
        type: "message",
        role: "assistant",
        content: `[Previous conversation summary]\n${summary}`,
      } as ResponseInputItem
    }

    // Strip encrypted_content from reasoning items — upstream can't verify
    // tokens generated by a different Copilot session/account
    if (
      record.type === "reasoning"
      && "encrypted_content" in record
      && !isModelFallbackActive()
    ) {
      const { encrypted_content: _, ...rest } = record
      return rest as ResponseInputItem
    }

    return item
  })
}

const findLatestCompactionIndex = (input: Array<ResponseInputItem>): number => {
  for (let index = input.length - 1; index >= 0; index -= 1) {
    const item = input[index] as Record<string, unknown>
    if (item.type === "compaction") return index
  }
  return -1
}

const preserveCompactionBootstrap = (
  input: Array<ResponseInputItem>,
  compactionIndex: number,
): Array<ResponseInputItem> => {
  const prefix = input.slice(0, compactionIndex)
  const latestTurnId = findLatestTurnId(prefix)
  const bootstrap = prefix.filter((item) => {
    const record = item as Record<string, unknown>
    return (
      record.type === "additional_tools"
      || (latestTurnId !== null && getTurnId(record) === latestTurnId)
    )
  })

  return [...bootstrap, ...input.slice(compactionIndex)]
}

const findLatestTurnId = (input: Array<ResponseInputItem>): string | null => {
  for (let index = input.length - 1; index >= 0; index -= 1) {
    const turnId = getTurnId(input[index] as Record<string, unknown>)
    if (turnId !== null) return turnId
  }
  return null
}

const getTurnId = (record: Record<string, unknown>): string | null => {
  const metadata = record.internal_chat_message_metadata_passthrough
  if (typeof metadata !== "object" || metadata === null) return null
  const turnId = (metadata as Record<string, unknown>).turn_id
  return typeof turnId === "string" && turnId.length > 0 ? turnId : null
}

/**
 * Try every available avenue to recover useful text from a compaction item.
 *
 * Priority:
 *  1. Proxy-generated items (cmp_ prefix) — base64-decode encrypted_content
 *  2. Any explicit "summary" or "text" field on the item
 *  3. Try base64-decoding encrypted_content even without cmp_ prefix
 *     (it may contain readable UTF-8 if generated by another compatible proxy)
 *  4. Leave opaque native compaction state intact
 */
const extractCompactionSummary = (
  record: Record<string, unknown>,
): string | null => {
  const id = typeof record.id === "string" ? record.id : ""
  const encrypted =
    typeof record.encrypted_content === "string" ?
      record.encrypted_content
    : null

  // 1. Proxy-generated items — base64 summary
  if (encrypted && id.startsWith("cmp_")) {
    const decoded = tryBase64DecodeReadable(encrypted)
    if (decoded) return decoded
  }

  // 2. Explicit summary / text fields some implementations attach
  const fromFields = extractSummaryFields(record)
  if (fromFields) return fromFields

  // 3. Speculatively try base64-decoding encrypted_content — even without
  //    cmp_ prefix it may be readable if generated by a compatible proxy
  if (encrypted) {
    const decoded = tryBase64DecodeReadable(encrypted)
    if (decoded) return decoded
  }

  // 4. Preserve opaque native state for the session-affine upstream account
  return null
}

/** Decode base64 and return text only if it looks like readable UTF-8. */
const tryBase64DecodeReadable = (data: string): string | null => {
  try {
    const decoded = new TextDecoder(undefined, { fatal: true }).decode(
      Buffer.from(data, "base64"),
    )
    if (!decoded) return null

    for (const character of decoded) {
      const codePoint = character.codePointAt(0) ?? 0
      const disallowedControl =
        (codePoint < 0x20 && ![0x0a, 0x0d, 0x09].includes(codePoint))
        || (codePoint >= 0x7f && codePoint <= 0x9f)
      if (disallowedControl) return null
    }

    return decoded
  } catch {
    return null
  }
}

/** Extract text from summary/text fields that some implementations attach. */
const extractSummaryFields = (
  record: Record<string, unknown>,
): string | null => {
  const parts: Array<string> = []
  if (Array.isArray(record.summary)) {
    for (const entry of record.summary) {
      const text = extractEntryText(entry)
      if (text) parts.push(text)
    }
  }
  if (typeof record.summary === "string" && record.summary) {
    parts.push(record.summary)
  }
  if (typeof record.text === "string" && record.text) {
    parts.push(record.text)
  }
  return parts.length > 0 ? parts.join("\n") : null
}

const extractEntryText = (entry: unknown): string | null => {
  if (typeof entry === "string") return entry
  if (
    typeof entry === "object"
    && entry !== null
    && typeof (entry as Record<string, unknown>).text === "string"
  ) {
    return (entry as Record<string, unknown>).text as string
  }
  return null
}
export const hasAgentInitiator = (payload: ResponsesPayload): boolean => {
  // Refactor `isAgentCall` logic to check only the last message in the history rather than any message. This prevents valid user messages from being incorrectly flagged as agent calls due to previous assistant history, ensuring proper credit consumption for multi-turn conversations.
  const lastItem = getPayloadItems(payload).at(-1)
  if (!lastItem) {
    return false
  }
  if (!("role" in lastItem) || !lastItem.role) {
    return true
  }
  const role =
    typeof lastItem.role === "string" ? lastItem.role.toLowerCase() : ""
  return role === "assistant"
}

export const hasVisionInput = (payload: ResponsesPayload): boolean => {
  const values = getPayloadItems(payload)
  return values.some((item) => containsVisionContent(item))
}

const getPayloadItems = (
  payload: ResponsesPayload,
): Array<ResponseInputItem> => {
  const result: Array<ResponseInputItem> = []

  const { input } = payload

  if (Array.isArray(input)) {
    result.push(...input)
  }

  return result
}

const containsVisionContent = (value: unknown): boolean => {
  if (!value) return false

  if (Array.isArray(value)) {
    return value.some((entry) => containsVisionContent(entry))
  }

  if (typeof value !== "object") {
    return false
  }

  const record = value as Record<string, unknown>
  const type =
    typeof record.type === "string" ? record.type.toLowerCase() : undefined

  if (type === "input_image" || type === "input_file") {
    return true
  }

  if (Array.isArray(record.content)) {
    return record.content.some((entry) => containsVisionContent(entry))
  }

  if (Array.isArray(record.output)) {
    return record.output.some((entry) => containsVisionContent(entry))
  }

  return false
}
